# Generated by Django 5.1.7 on 2025-03-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "verbose_name": "Актеры и режиссеры",
                "verbose_name_plural": "Актеры и режиссеры",
            },
        ),
        migrations.AlterModelOptions(
            name="movieshots",
            options={
                "verbose_name": "Кадр из фильма",
                "verbose_name_plural": "Кадры из фильма",
            },
        ),
    ]
